# Site settings
title: Cornerstone
email: kifile@kifile.com
baseurl: "/Cornerstone" # the subpath of your site, e.g. /blog/
url: "http://kifile.github.io" # the base hostname & protocol for your site
github_username:  kifile

# Build settings
markdown: kramdown
